
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MUGHAL TRADERS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Incorrect.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Closs = new javax.swing.JButton();
        Login = new javax.swing.JLabel();
        Incorrect = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Loginbtn = new javax.swing.JButton();
        Showpas = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Closs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        Closs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClossActionPerformed(evt);
            }
        });
        getContentPane().add(Closs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        Login.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 255));
        Login.setText("LOGIN");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        Incorrect.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Incorrect.setForeground(new java.awt.Color(255, 51, 102));
        Incorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        Incorrect.setText("incorrect Username or Passwrd");
        getContentPane().add(Incorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 231, -1));

        Username.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(51, 51, 255));
        Username.setText("Enter Username");
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 260, -1));

        Password.setForeground(new java.awt.Color(51, 51, 255));
        Password.setText("Enter Password");
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 260, -1));

        Loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(51, 51, 255));
        Loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        Loginbtn.setText("Login");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        Showpas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Showpas.setForeground(new java.awt.Color(51, 51, 255));
        Showpas.setText("Show Password");
        Showpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowpasActionPerformed(evt);
            }
        });
        getContentPane().add(Showpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed
    // Username or Password Events
    
   //
    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        // TODO add your handling code here:
        Incorrect.setVisible(false);
        if(Username.getText().equals("Enter Username"))
        {
            Username.setText("");
            Username.setForeground(new Color(0,118,221));
            
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        // TODO add your handling code here:
         Incorrect.setVisible(false);
         if(Username.getText().equals(""))
         {
             Username.setText("Enter Username");
             Username.setForeground(new Color(0,118,221));
         }
    }//GEN-LAST:event_UsernameFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // TODO add your handling code here:
         Incorrect.setVisible(false);
        if(Password.getText().equals("Enter Password"))
        {
            Password.setText("");
            Password.setForeground(new Color(0,118,221));
            
        }
    }//GEN-LAST:event_PasswordFocusGained
//
//    private void UsernameFocusLost(java.awt.event.FocusEvent evt)
//    private void UsernameFocusLost(java.awt.event.FocusEvent evt)
    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
         Incorrect.setVisible(false);
         if(Password.getText().equals(""))
         {
             Password.setText("Enter Password");
             Password.setForeground(new Color(0,118,221));
         }
    }//GEN-LAST:event_PasswordFocusLost

    //Clossbtn Event
    private void ClossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClossActionPerformed
        // TODO add your handling code here:
        
        int a = JOptionPane.showConfirmDialog(null, "Kya waqa hi jana chahta ho, sach bata oo", "Select", JOptionPane.YES_NO_OPTION);
         if (a == JOptionPane.YES_OPTION) {
        System.exit(0); // Close the application if "Yes" is selected.
    }

    }//GEN-LAST:event_ClossActionPerformed

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // TODO add your handling code here:
        if(Username.getText().equals("Ejaz") && Password.getText().equals("admin")){
            setVisible(false);
            new Home().setVisible(true);
        }else{
            Incorrect.setVisible(true);
        }
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void ShowpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowpasActionPerformed
        // TODO add your handling code here:
        if(Showpas.isSelected()){
            Password.setEchoChar((char)0);
        }else{
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowpasActionPerformed
        // Events of Username and Passwords Complete here
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Closs;
    private javax.swing.JLabel Incorrect;
    private javax.swing.JLabel Login;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JPasswordField Password;
    private javax.swing.JCheckBox Showpas;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
